# Generated by Django 5.2.4 on 2025-07-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_jobpost_resumeupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeupload',
            name='job',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
        migrations.DeleteModel(
            name='ResumeUpload',
        ),
    ]
