# Generated by Django 5.2.4 on 2025-07-16 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_jobpost_resumeupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeupload',
            name='linkedin_url',
        ),
    ]
