# Generated by Django 5.2.4 on 2025-07-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_remove_resumeupload_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeupload',
            name='shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
