# Generated by Django 5.2.4 on 2025-07-28 05:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_resumeupload_shortlisted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='resumeupload',
            options={'ordering': ['-ranking_score', '-skill_match_percentage', '-score', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='jobpost',
            name='applications_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (2-5 years)'), ('senior', 'Senior Level (5+ years)'), ('lead', 'Lead/Principal (8+ years)')], default='mid', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full-time', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='min_score_threshold',
            field=models.IntegerField(default=50, help_text='Minimum overall score threshold'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='remote_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skill_match_threshold',
            field=models.IntegerField(default=60, help_text='Minimum skill match percentage for top candidates'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills_preferred',
            field=models.TextField(blank=True, help_text='Comma-separated preferred skills'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('500+', '500+ employees')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='candidate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='extracted_skills',
            field=models.TextField(blank=True, help_text='Comma-separated extracted skills', null=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='hr_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='interview_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='ranking_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='skill_match_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='skills_required',
            field=models.TextField(help_text='Comma-separated required skills'),
        ),
        migrations.AlterField(
            model_name='resumeupload',
            name='score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterUniqueTogether(
            name='resumeupload',
            unique_together={('job', 'candidate_email')},
        ),
        migrations.CreateModel(
            name='CompanyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_jobs_posted', models.IntegerField(default=0)),
                ('active_jobs', models.IntegerField(default=0)),
                ('total_applications_received', models.IntegerField(default=0)),
                ('applications_this_month', models.IntegerField(default=0)),
                ('candidates_shortlisted', models.IntegerField(default=0)),
                ('candidates_hired', models.IntegerField(default=0)),
                ('average_candidate_score', models.FloatField(default=0.0)),
                ('average_skill_match', models.FloatField(default=0.0)),
                ('average_time_to_hire', models.IntegerField(default=0, help_text='Days')),
                ('profile_views', models.IntegerField(default=0)),
                ('job_views', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='resume.profile')),
            ],
        ),
    ]
