# Generated by Django 5.2.4 on 2025-07-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_jobpost_options_alter_resumeupload_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeupload',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Resume Upload', 'verbose_name_plural': 'Resume Uploads'},
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('interview_scheduled', 'Interview Scheduled'), ('hired', 'Hired')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
